
export const CONFIG = {
    ITEMS_PER_PAGE: 4,
    ITEMS_PER_PAGE_MAIN_PRODUCTS:4,
    ITEMS_PER_PAGE_MAIN_ARTICLES:3,
    CARD_DISCOUNT_PERCENT:6,
    ITEMS_PER_PAGE_CATEGORY:8,
    FALLBACK_PRICE_RANGE:{min:0 , max:3000},
    SITE_URL: "https://delivery-shop.ua",
    TEMPORARY_EMAIL_DOMAIN: "@delivery-shop.ua",
}